remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Predicting Country of Origin from Recipes]
description: [This site is to document our project on predicting th country of origin of a recipe based on features of the recipe]